name: Publish

env:
  PYPI_USER_NAME: simaki

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry

    - name: Publish
      run: |
        python3 -m poetry publish --build --username ${PYPI_USER_NAME} --password ${{ secrets.PYPI_PASSWORD }}
